/**
 * @fileoverview Which Firebase project a deploy or a script is allowed to touch.
 *
 * The browser used to carry the church project id in three copies, and the
 * prod workflow trusted `.firebaserc` default. Either one can aim a ghost
 * URL at the church database. The catalog in config/firebase-projects.json
 * is the only copy. `apply-firebase-project.js` writes the files Hosting and
 * Functions actually ship. `check-firebase-deploy.js` refuses the deploy
 * when those files disagree with `--project`.
 *
 * Scripts call `requireProject(process.argv)`. The church project additionally
 * needs `--i-mean-prod`, so a forgotten flag cannot write it.
 */

const fs = require('fs');
const path = require('path');

const PROD_PROJECT_ID = 'mosaic-hymn-database';

function catalogPath(root) {
    return path.join(root, 'config', 'firebase-projects.json');
}

function loadCatalog(root) {
    return JSON.parse(fs.readFileSync(catalogPath(root), 'utf8'));
}

function loadProject(root, projectId) {
    const catalog = loadCatalog(root);
    const project = catalog[projectId];
    if (!project || project.projectId !== projectId) {
        throw new Error(
            `Unknown Firebase project "${projectId}". ` +
            'It has to be a key in config/firebase-projects.json.');
    }
    return project;
}

function webConfig(project, appName) {
    const app = project.apps && project.apps[appName];
    if (!app) {
        throw new Error(`No "${appName}" web app on ${project.projectId}.`);
    }
    const config = {
        apiKey: project.apiKey,
        authDomain: project.authDomain,
        projectId: project.projectId,
        storageBucket: project.storageBucket,
        messagingSenderId: app.messagingSenderId,
        appId: app.appId,
    };
    if (app.measurementId) config.measurementId = app.measurementId;
    return config;
}

function flagValue(argv, name) {
    const at = argv.indexOf(name);
    if (at < 0) return null;
    const value = argv[at + 1];
    if (!value || value.startsWith('--')) return null;
    return value;
}

/**
 * The project a script is allowed to touch.
 *
 * @param {string[]} argv process.argv
 * @param {{root?: string, hardcoded?: string}} [options]
 *   `hardcoded` is for a script whose key file is still baked to one project.
 *   Passing a different `--project` throws, instead of loading that key and
 *   aiming it somewhere else.
 * @returns {string}
 */
function requireProject(argv, options = {}) {
    const root = options.root || path.join(__dirname, '..');
    const projectId = flagValue(argv, '--project');
    if (!projectId) {
        throw new Error(
            'Pass --project <id>. The church project also needs --i-mean-prod.');
    }
    loadProject(root, projectId);
    if (projectId === PROD_PROJECT_ID && !argv.includes('--i-mean-prod')) {
        throw new Error(
            `Refusing to touch ${PROD_PROJECT_ID} without --i-mean-prod.`);
    }
    if (options.hardcoded && options.hardcoded !== projectId) {
        throw new Error(
            `This script only talks to ${options.hardcoded}, not ${projectId}.`);
    }
    return projectId;
}

function renderBrowserConfig(project) {
    const body = {
        projectId: project.projectId,
        church: webConfig(project, 'church'),
        form: webConfig(project, 'form'),
        liveOrigin: project.liveOrigin,
    };
    return [
        '// Generated by scripts/apply-firebase-project.js from config/firebase-projects.json.',
        '// Do not edit by hand. A deploy fails when this projectId disagrees with --project.',
        'window.MosaicFirebaseProject = ' + JSON.stringify(body, null, 2) + ';',
        '',
    ].join('\n');
}

function functionsProject(project) {
    const church = webConfig(project, 'church');
    return {
        projectId: project.projectId,
        storageBucket: project.storageBucket,
        smsReplyWebhookUrl: project.smsReplyWebhookUrl,
        mcpIssuerUrl: project.mcpIssuerUrl,
        mcpWeb: {
            apiKey: church.apiKey,
            authDomain: church.authDomain,
            projectId: church.projectId,
        },
    };
}

function readBrowserProject(sourceOrPath) {
    const src = sourceOrPath.includes('\n') || sourceOrPath.includes('window.')
        ? sourceOrPath
        : fs.readFileSync(sourceOrPath, 'utf8');
    const match = src.match(/window\.MosaicFirebaseProject = (\{[\s\S]*\});?\s*$/);
    if (!match) {
        throw new Error('public/firebase-config.js has no MosaicFirebaseProject assignment.');
    }
    return JSON.parse(match[1]);
}

function assertDeploy({root, projectId, iMeanProd}) {
    const errors = [];
    let project;
    try {
        project = loadProject(root, projectId);
    } catch (err) {
        throw err;
    }
    if (projectId === PROD_PROJECT_ID && !iMeanProd) {
        errors.push(`Refusing to deploy ${PROD_PROJECT_ID} without --i-mean-prod.`);
    }

    const browserPath = path.join(root, 'public', 'firebase-config.js');
    let shipped;
    try {
        shipped = readBrowserProject(browserPath);
    } catch (err) {
        errors.push(err.message);
    }
    if (shipped && shipped.projectId !== projectId) {
        errors.push(
            `public/firebase-config.js says ${shipped.projectId}, ` +
            `but this deploy is --project ${projectId}.`);
    }
    if (shipped && project) {
        const church = webConfig(project, 'church');
        const form = webConfig(project, 'form');
        if (JSON.stringify(shipped.church) !== JSON.stringify(church) ||
            JSON.stringify(shipped.form) !== JSON.stringify(form) ||
            shipped.liveOrigin !== project.liveOrigin) {
            errors.push('public/firebase-config.js has drifted from config/firebase-projects.json.');
        }
    }

    const fnPath = path.join(root, 'functions', 'firebase-project.json');
    if (!fs.existsSync(fnPath)) {
        errors.push('functions/firebase-project.json is missing.');
    } else if (project) {
        const fn = JSON.parse(fs.readFileSync(fnPath, 'utf8'));
        const expected = functionsProject(project);
        if (JSON.stringify(fn) !== JSON.stringify(expected)) {
            errors.push(
                'functions/firebase-project.json has drifted from the catalog ' +
                `for ${projectId}.`);
        }
    }

    const firebaseJsonPath = path.join(root, 'firebase.json');
    const rcPath = path.join(root, '.firebaserc');
    if (fs.existsSync(firebaseJsonPath) && fs.existsSync(rcPath) && project) {
        const firebaseJson = JSON.parse(fs.readFileSync(firebaseJsonPath, 'utf8'));
        const rc = JSON.parse(fs.readFileSync(rcPath, 'utf8'));
        const hosting = firebaseJson.hosting || [];
        if (!hosting.some(h => h.target === 'church') ||
            !hosting.some(h => h.target === 'mcp')) {
            errors.push(
                'firebase.json hosting must name targets "church" and "mcp", ' +
                'not hardcoded site ids.');
        }
        for (const entry of hosting) {
            if (entry.site === project.hosting.church || entry.site === project.hosting.mcp) {
                errors.push(
                    `firebase.json still hardcodes site "${entry.site}". ` +
                    'Use a hosting target so a second project can map its own sites.');
            }
        }
        const mapped = ((rc.targets || {})[projectId] || {}).hosting || {};
        const churchSite = (mapped.church || [])[0];
        const mcpSite = (mapped.mcp || [])[0];
        if (churchSite !== project.hosting.church) {
            errors.push(
                `The church hosting target for ${projectId} is "${churchSite}", ` +
                `catalog says "${project.hosting.church}".`);
        }
        if (mcpSite !== project.hosting.mcp) {
            errors.push(
                `The mcp hosting target for ${projectId} is "${mcpSite}", ` +
                `catalog says "${project.hosting.mcp}".`);
        }
    }

    if (project) {
        const indexPath = path.join(root, 'functions', 'index.js');
        if (fs.existsSync(indexPath) && projectId === PROD_PROJECT_ID) {
            const indexJs = fs.readFileSync(indexPath, 'utf8');
            const issuer = indexJs.match(
                /defineString\(\s*"MCP_ISSUER_URL"[\s\S]*?default:\s*"([^"]+)"/);
            if (!issuer || issuer[1] !== project.mcpIssuerUrl) {
                errors.push(
                    'MCP_ISSUER_URL default in functions/index.js does not match the catalog.');
            }
        }
        // The committed App Check file names the church origin. A ghost leaves
        // App Check off (PUBLIC_FORM_APP_CHECK_MODE=off), so that literal is
        // not rewritten and is not required to match the ghost origin.
        const appCheckPath = path.join(root, 'public', 'app-check-config.js');
        if (fs.existsSync(appCheckPath) && projectId === PROD_PROJECT_ID) {
            const appCheck = fs.readFileSync(appCheckPath, 'utf8');
            const live = `liveOrigin: '${project.liveOrigin}'`;
            if (!appCheck.includes(live)) {
                errors.push(
                    'App Check liveOrigin in public/app-check-config.js does not match the catalog.');
            }
        }
        const envPath = path.join(root, 'functions', `.env.${projectId}`);
        if (fs.existsSync(envPath)) {
            const env = fs.readFileSync(envPath, 'utf8');
            const issuer = env.match(/^MCP_ISSUER_URL=(.*)$/m);
            if (!issuer || issuer[1].trim() !== project.mcpIssuerUrl) {
                errors.push(
                    `MCP_ISSUER_URL in functions/.env.${projectId} does not match the catalog.`);
            }
        } else if (projectId !== PROD_PROJECT_ID) {
            errors.push(
                `functions/.env.${projectId} is missing. A non-church deploy must set MCP_ISSUER_URL.`);
        }
    }

    if (errors.length) {
        throw new Error(errors.join('\n'));
    }
}

module.exports = {
    PROD_PROJECT_ID,
    loadProject,
    webConfig,
    requireProject,
    renderBrowserConfig,
    functionsProject,
    readBrowserProject,
    assertDeploy,
};
