#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# The wizard's own memory, so a re-run offers what you typed last time.
# Gitignored — the site key itself is written to public/app-check-config.js,
# which IS committed, because a reCAPTCHA site key is public by design.
ENV_FILE=".app-check.local"

PROJECT_ID="mosaic-hymn-database"
CONFIG_FILE="public/app-check-config.js"

TOTAL_STAGES=6

banner "App Check for Mosaic's public forms"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "What this is, and why the form is refusing everything"
say "A public form lives at an address anybody can reach. That is the point —"
say "it is for people outside the church. But nothing about that address says"
say "the request came from a real person on your page, so a script could fill"
say "a bible study sign-up with rubbish a thousand times a second."
say ""
say "App Check has the browser quietly collect a token proving it is running"
say "YOUR website. The server refuses anything that arrives without one."
say "Whoever fills the form in sees nothing at all — no 'tick to prove you"
say "are human'."
say ""
warn "Until this is done, public forms refuse EVERY answer, including real ones."
note "Members-only forms are unaffected — they are already protected by sign-in."
say ""
say "You will need about five minutes and a browser signed in to Firebase."
pause "Ready?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Make the reCAPTCHA key FIRST, in Google Cloud"
warn "Firebase does NOT create this key. Its App Check screen only has a box"
warn "to paste one into, so going there first leaves you stuck on a Save"
warn "button that will not go."
say ""
say "Opening reCAPTCHA Enterprise for the $PROJECT_ID project."
open_url "https://console.cloud.google.com/security/recaptcha?project=${PROJECT_ID}"
say ""
step "If it offers to enable the reCAPTCHA Enterprise API, do that first."
step "Create key."
step "Display name: anything. mosaic-app-check does."
step "Application type: WEBSITE."
step "Domains: the church's live domain, plus localhost so you can test."
step "Turn OFF the checkbox challenge — App Check wants the invisible,"
step "score-based kind, not the 'I am not a robot' tickbox."
step "Create, then copy the Key ID. It starts 6L."
say ""
note "Billing: reCAPTCHA Enterprise needs a billing account on the project."
note "This one has one already — v2 Cloud Functions require the Blaze plan —"
note "so it should not ask. If it does, stop and say so."
note ""
note "Fallback: App Check also offers a plain 'reCAPTCHA' provider (the older"
note "v3). Its keys come from google.com/recaptcha/admin instead, need no"
note "billing, and are fine here. Take it if Enterprise fights you."
pause "Got a key starting 6L?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Hand the key to Firebase App Check"
open_url "https://console.firebase.google.com/project/${PROJECT_ID}/appcheck/apps"
say ""
step "Find the WEB app in the list — hymn_database. It will say Unregistered."
step "Expand reCAPTCHA Enterprise and paste the key you just made."
step "Leave Token time to live at 1 hour."
step "Save."
say ""
warn "Console labels move. If the wording differs, follow the intent: the web"
warn "app ends up Registered, against a key you made in the previous stage."
pause "Registered?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Save the key into the repo"
say "The site key is public — it ships in every browser that loads the page,"
say "exactly like the Firebase apiKey already in auth.js. It goes into the"
say "repo, and it is NOT a secret."
note "The secret half stays in Google's console and never comes near this repo."
say ""
say "It usually looks like: 6Lc................................"
ask APP_CHECK_SITE_KEY "Paste the reCAPTCHA site key:"

if [[ -z "${APP_CHECK_SITE_KEY:-}" ]]; then
  warn "Nothing pasted, so nothing was written."
  SKIPPED+=("the site key — re-run this wizard when you have it")
else
  write_env APP_CHECK_SITE_KEY "$APP_CHECK_SITE_KEY"
  # Rewrite only the siteKey line, so the file's comments survive.
  tmp_cfg=$(mktemp)
  sed "s|siteKey: '.*',|siteKey: '${APP_CHECK_SITE_KEY}',|" "$CONFIG_FILE" > "$tmp_cfg"
  mv "$tmp_cfg" "$CONFIG_FILE"
  printf '  %s✓ wrote%s siteKey → %s\n' "$GREEN" "$RESET" "$CONFIG_FILE"
  if grep -q "siteKey: '${APP_CHECK_SITE_KEY}'" "$CONFIG_FILE"; then
    say "Verified in the file."
  else
    warn "The file did not take the key. Edit $CONFIG_FILE by hand."
    SKIPPED+=("siteKey in $CONFIG_FILE — set it by hand")
  fi
fi
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "A debug token, so you can test before it is live"
say "On localhost the browser cannot prove it is the real site, so App Check"
say "would refuse you too. A debug token is how Google lets a developer"
say "through without weakening anything for anybody else."
say ""
step "Open the answering page on localhost with the browser console visible."
step "Firebase prints a debug token there the first time it runs."
step "Back in the Firebase console, on your web app, add that token under"
step "the app's debug tokens."
say ""
note "Skip this if you only plan to test against the deployed site."
warn "A debug token is a real bypass. Never paste one into a page, a commit,"
warn "or a screenshot — it belongs only in the Firebase console."
pause "Done, or skipping"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Deploy, and check it actually works"
say "The server has enforced App Check since MS-367. It is the browser half"
say "that was missing, and it is now in the repo — so this deploy is what"
say "makes a public form answerable."
say ""
if confirm "Deploy hosting and the publicForm function now?"; then
  say "Deploying. This takes a couple of minutes."
  if firebase deploy --only hosting,functions:publicForm --project "$PROJECT_ID"; then
    say ""
    printf '  %s✓ deployed%s\n' "$GREEN" "$RESET"
  else
    warn "The deploy failed. Nothing here is lost — fix the error and re-run."
    SKIPPED+=("firebase deploy --only hosting,functions:publicForm")
  fi
else
  SKIPPED+=("firebase deploy --only hosting,functions:publicForm")
  note "Nothing deployed. The site key is saved and waiting."
fi
say ""
say "To check it: publish a public form, open its link on a phone with wifi"
say "off, and answer it. If it goes through, App Check is working."
note "Commit public/app-check-config.js — the key belongs in the repo."
pause

finish
